on:
  push:
    branches:
      - 'master'
      
name: Tests
jobs:
  runTests:
    name: My test
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name length
        if: ${{echo 'Portillla77/VCOSSB-172/Fix_solution_based_on_averages' | wc -c > 30}}
        run: |
          echo '::set-env name=TAG::$(echo 'Portillla77/VCOSSB-172/Fix_solution_based_on_averages' | grep -o -P "^.+/" | sed 's+/$++' | tr '[:upper:]' '[:lower:]' | sed "s+/+-+g")'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Set tag
        if: $(echo 'Portillla77/VCOSSB-172/Fix_solution_based_on_averages' | wc -c) < 30
        run: echo '::set-env name=TAG::$(echo 'Portillla77/VCOSSB-172/Fix_solution_based_on_averages' | tr '[:upper:]' '[:lower:]' | sed "s+/+-+g")'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: run test
        run: echo $TAG
          
    
