on:
  push:
    branches:
      - 'master'
      
name: Tests
jobs:
  runTests:
    name: My test
    runs-on: ubuntu-latest
    steps:
      - name: One step
        env:
          thebranch: Portillla77/VCOSSB-172/Fix_solution_based_on_averages
        run: |
          if [[ $(echo $thebranch | wc -c) > 30 ]]; then
            echo '::set-env name=TAG::$(echo $thebranch | grep -o -P "^.+/" | sed 's+/$++' | tr '[:upper:]' '[:lower:]' | sed "s+/+-+g")'
          else
            echo '::set-env name=TAG::$(echo $thebranch | tr '[:upper:]' '[:lower:]' | sed "s+/+-+g")'
          fi
      - name: run test
        run: echo $TAG
          
    
