on:
  push:
    branches:
      - 'master'
      
name: Tests
jobs:
  runTests:
    name: My test
    runs-on: ubuntu-latest
    steps:
      - name: set env
        env:
          bn: 'hello/world/algo'
        run: echo "BRANCH_NAME=$(var="echo 'hello/world/algo' | wc -c" |  if $var > 3; then echo "$bn" | grep -o -P "^.+/" | sed 's+/$++'; fi)" >> $GITHUB_ENV
      - name: run test
        run: echo $BRANCH_NAME
          
    
