on:
  push:
    branches:
      - 'master'
      
name: Tests
jobs:
  runTests:
    name: My test
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name length
        if: $(echo ${{ secrets.BRANCH }} | wc -c) > 30
        run: |
          echo '::set-env name=TAG::$(echo ${{ secrets.BRANCH }} | grep -o -P "^.+/" | sed 's+/$++' | tr '[:upper:]' '[:lower:]' | sed "s+/+-+g")'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Set tag
        if: $(echo ${{ secrets.BRANCH }} | wc -c) < 30
        run: echo '::set-env name=TAG::$(echo ${{ secrets.BRANCH }} | tr '[:upper:]' '[:lower:]' | sed "s+/+-+g")'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: run test
        run: echo $TAG
          
    
